changed the config file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,10 +49,12 @@ jobs:
 
     - name: Run golint
       run: |
+            default=0
             warnings=`golint ./... | wc -l`
-            if [$warnings != 0]; then
-              echo "one or more formatting mistakes found..."
-              exit 1
+            echo "Warnings : $warnings"
+            if (( $(echo "$warnings $default" | awk '{print ($1 > $2)}') )); then
+                echo "formatting error..."
+                exit 1
             else
               echo "OK"  
             fi
